#!/usr/bin/env python3
"""
Enrich destination JSON files with hardcoded travel data.

Populates: best_months, recommended_days, rough_cost, flight_duration_from_sfo,
cost_breakdown, seasonal_note, safety_rating, visa_required, child_friendly, elderly_friendly.

Usage:
    python tools/enrich_destinations.py
    python tools/enrich_destinations.py --dry-run   # Preview without writing
"""

import argparse
import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
DATA_DIR = PROJECT_ROOT / "data" / "destinations"

# ── Lookup table keyed by slug (filename without .json) ─────────────────────
# Fields: bm=best_months, rd=recommended_days, rc=rough_cost, fl=flight_duration,
#         cb=cost_breakdown, sn=seasonal_note, sr=safety_rating, vr=visa_required,
#         cf=child_friendly, ef=elderly_friendly

ENRICHMENT = {
    "alaska-summer": {
        "bm": ["Jun", "Jul", "Aug"],
        "rd": 10,
        "rc": "$3,000–$5,000",
        "fl": "4h direct",
        "cb": {"flights": 600, "hotels": 1500, "food": 600, "activities": 800},
        "sn": "Longest daylight, wildlife active, glaciers accessible, cruise season.",
        "sr": "High",
        "vr": "No (domestic)",
        "cf": "Qualified",
        "ef": "Qualified",
    },
    "amalfi-coast-italy-summer": {
        "bm": ["May", "Jun", "Sep", "Oct"],
        "rd": 7,
        "rc": "$3,500–$5,500",
        "fl": "14h 1-stop",
        "cb": {"flights": 1200, "hotels": 1500, "food": 500, "activities": 400},
        "sn": "Warm Mediterranean weather, perfect for coastal drives and boat tours.",
        "sr": "High",
        "vr": "No (90-day Schengen)",
        "cf": "Qualified",
        "ef": "Qualified",
    },
    "amsterdam-netherlands-summer": {
        "bm": ["Apr", "May", "Jun", "Jul", "Aug", "Sep"],
        "rd": 5,
        "rc": "$2,500–$4,000",
        "fl": "11h direct",
        "cb": {"flights": 900, "hotels": 1000, "food": 400, "activities": 300},
        "sn": "Long days, canal-side terraces, tulip aftermath, outdoor festivals.",
        "sr": "High",
        "vr": "No (90-day Schengen)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "angkor-wat-cambodia-summer": {
        "bm": ["Nov", "Dec", "Jan", "Feb", "Mar"],
        "rd": 5,
        "rc": "$1,500–$2,500",
        "fl": "18h 1-stop",
        "cb": {"flights": 800, "hotels": 350, "food": 150, "activities": 200},
        "sn": "Summer is rainy season—fewer crowds, lush greenery, dramatic skies.",
        "sr": "Moderate",
        "vr": "Visa on arrival ($30)",
        "cf": "Qualified",
        "ef": "Qualified",
    },
    "athens-greece-summer": {
        "bm": ["Apr", "May", "Jun", "Sep", "Oct"],
        "rd": 7,
        "rc": "$2,500–$4,000",
        "fl": "14h 1-stop",
        "cb": {"flights": 1000, "hotels": 800, "food": 400, "activities": 300},
        "sn": "Warm but not peak-heat; ideal for ruins, islands, and outdoor dining.",
        "sr": "High",
        "vr": "No (90-day Schengen)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "azores-portugal-summer": {
        "bm": ["Jun", "Jul", "Aug", "Sep"],
        "rd": 8,
        "rc": "$2,000–$3,500",
        "fl": "10h 1-stop",
        "cb": {"flights": 800, "hotels": 700, "food": 350, "activities": 400},
        "sn": "Warmest months, whale watching season, hydrangeas in bloom.",
        "sr": "High",
        "vr": "No (90-day Schengen)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "bali-indonesia-summer": {
        "bm": ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct"],
        "rd": 10,
        "rc": "$2,000–$3,500",
        "fl": "17h 1-stop",
        "cb": {"flights": 900, "hotels": 600, "food": 300, "activities": 300},
        "sn": "Dry season: best for temples, rice terraces, beaches, and diving.",
        "sr": "High",
        "vr": "No (30-day visa-free)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "banff-canada-summer": {
        "bm": ["Jun", "Jul", "Aug", "Sep"],
        "rd": 7,
        "rc": "$2,500–$4,000",
        "fl": "4h 1-stop",
        "cb": {"flights": 500, "hotels": 1200, "food": 500, "activities": 400},
        "sn": "All trails open, turquoise lakes thawed, wildlife active.",
        "sr": "High",
        "vr": "No (eTA required)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "bangkok-thailand-summer": {
        "bm": ["Nov", "Dec", "Jan", "Feb", "Mar"],
        "rd": 7,
        "rc": "$1,800–$3,000",
        "fl": "17h 1-stop",
        "cb": {"flights": 800, "hotels": 500, "food": 250, "activities": 200},
        "sn": "Summer is hot and rainy—but fewer tourists, lower prices, green landscapes.",
        "sr": "Moderate",
        "vr": "No (30-day visa-free)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "barcelona-spain-summer": {
        "bm": ["May", "Jun", "Sep", "Oct"],
        "rd": 7,
        "rc": "$2,500–$4,000",
        "fl": "12h direct",
        "cb": {"flights": 900, "hotels": 900, "food": 450, "activities": 350},
        "sn": "Beach weather, outdoor dining, vibrant nightlife, Gaudí at golden hour.",
        "sr": "Moderate",
        "vr": "No (90-day Schengen)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "berlin-germany-summer": {
        "bm": ["May", "Jun", "Jul", "Aug", "Sep"],
        "rd": 6,
        "rc": "$2,200–$3,500",
        "fl": "12h direct",
        "cb": {"flights": 900, "hotels": 700, "food": 350, "activities": 300},
        "sn": "Warm, long days, outdoor beer gardens, festivals, open-air galleries.",
        "sr": "High",
        "vr": "No (90-day Schengen)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "bhutan-summer": {
        "bm": ["Mar", "Apr", "May", "Sep", "Oct", "Nov"],
        "rd": 10,
        "rc": "$4,000–$6,000",
        "fl": "20h 2-stop",
        "cb": {"flights": 1500, "hotels": 1500, "food": 400, "activities": 600},
        "sn": "Summer monsoon brings lush valleys; spring/fall are peak trekking seasons.",
        "sr": "High",
        "vr": "Visa required (arranged by tour operator)",
        "cf": "Qualified",
        "ef": "No",
    },
    "bologna-italy-summer": {
        "bm": ["Apr", "May", "Jun", "Sep", "Oct"],
        "rd": 5,
        "rc": "$2,500–$3,800",
        "fl": "13h 1-stop",
        "cb": {"flights": 1000, "hotels": 800, "food": 500, "activities": 250},
        "sn": "Shoulder season best; summer is hot but locals leave—more authentic.",
        "sr": "High",
        "vr": "No (90-day Schengen)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "borneo-malaysia-summer": {
        "bm": ["Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct"],
        "rd": 10,
        "rc": "$2,500–$4,000",
        "fl": "18h 1-stop",
        "cb": {"flights": 1000, "hotels": 700, "food": 300, "activities": 500},
        "sn": "Dry season: best for jungle treks, orangutan encounters, and diving.",
        "sr": "Moderate",
        "vr": "No (90-day visa-free)",
        "cf": "Qualified",
        "ef": "No",
    },
    "budapest-hungary-summer": {
        "bm": ["May", "Jun", "Jul", "Aug", "Sep"],
        "rd": 5,
        "rc": "$1,800–$3,000",
        "fl": "13h 1-stop",
        "cb": {"flights": 900, "hotels": 500, "food": 300, "activities": 250},
        "sn": "Warm thermal baths outdoors, ruin bars, Danube sunsets.",
        "sr": "High",
        "vr": "No (90-day Schengen)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "buenos-aires-argentina": {
        "bm": ["Mar", "Apr", "May", "Sep", "Oct", "Nov"],
        "rd": 7,
        "rc": "$2,000–$3,500",
        "fl": "13h direct",
        "cb": {"flights": 900, "hotels": 600, "food": 350, "activities": 250},
        "sn": "Year-round city; spring/fall (Sep–Nov, Mar–May) most pleasant.",
        "sr": "Moderate",
        "vr": "No (90-day visa-free)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "cairo-luxor-egypt": {
        "bm": ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
        "rd": 10,
        "rc": "$2,000–$3,500",
        "fl": "16h 1-stop",
        "cb": {"flights": 900, "hotels": 500, "food": 250, "activities": 400},
        "sn": "Cooler months best for pyramids and Valley of the Kings.",
        "sr": "Moderate",
        "vr": "Visa on arrival ($25)",
        "cf": "Qualified",
        "ef": "Qualified",
    },
    "cape-town-south-africa": {
        "bm": ["Nov", "Dec", "Jan", "Feb", "Mar"],
        "rd": 10,
        "rc": "$2,500–$4,000",
        "fl": "20h 1-stop",
        "cb": {"flights": 1200, "hotels": 700, "food": 350, "activities": 400},
        "sn": "Southern hemisphere summer; Table Mountain, penguins, wine country.",
        "sr": "Moderate",
        "vr": "No (90-day visa-free)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "colombia-summer": {
        "bm": ["Dec", "Jan", "Feb", "Mar", "Jul", "Aug"],
        "rd": 12,
        "rc": "$2,000–$3,500",
        "fl": "8h direct",
        "cb": {"flights": 600, "hotels": 600, "food": 300, "activities": 400},
        "sn": "Dry seasons ideal for Cartagena, coffee region, and Medellín.",
        "sr": "Moderate",
        "vr": "No (90-day visa-free)",
        "cf": "Qualified",
        "ef": "Qualified",
    },
    "copenhagen-denmark-summer": {
        "bm": ["Jun", "Jul", "Aug"],
        "rd": 5,
        "rc": "$3,000–$4,500",
        "fl": "11h direct",
        "cb": {"flights": 900, "hotels": 1200, "food": 500, "activities": 300},
        "sn": "Long daylight, Tivoli open, cycling weather, harbor swimming.",
        "sr": "High",
        "vr": "No (90-day Schengen)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "corsica-france-summer": {
        "bm": ["Jun", "Jul", "Aug", "Sep"],
        "rd": 8,
        "rc": "$2,800–$4,200",
        "fl": "14h 1-stop",
        "cb": {"flights": 1100, "hotels": 1000, "food": 450, "activities": 350},
        "sn": "Beach season, GR20 hiking, Mediterranean perfection.",
        "sr": "High",
        "vr": "No (90-day Schengen)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "costa-rica-summer": {
        "bm": ["Dec", "Jan", "Feb", "Mar", "Apr"],
        "rd": 10,
        "rc": "$2,500–$4,000",
        "fl": "6h direct",
        "cb": {"flights": 500, "hotels": 800, "food": 400, "activities": 600},
        "sn": "Dry season best; summer (Jun–Aug) is green season—lush, fewer tourists.",
        "sr": "High",
        "vr": "No (90-day visa-free)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "cusco-peru-summer": {
        "bm": ["May", "Jun", "Jul", "Aug", "Sep"],
        "rd": 7,
        "rc": "$2,000–$3,500",
        "fl": "12h 1-stop",
        "cb": {"flights": 700, "hotels": 500, "food": 250, "activities": 400},
        "sn": "Dry season: clear skies for Inca sites and rainbow mountains.",
        "sr": "Moderate",
        "vr": "No (183-day visa-free)",
        "cf": "Qualified",
        "ef": "No",
    },
    "dolomites-italy-summer": {
        "bm": ["Jun", "Jul", "Aug", "Sep"],
        "rd": 7,
        "rc": "$2,500–$4,000",
        "fl": "13h 1-stop",
        "cb": {"flights": 1000, "hotels": 900, "food": 400, "activities": 350},
        "sn": "Hiking season, rifugios open, wildflower meadows, via ferrata routes.",
        "sr": "High",
        "vr": "No (90-day Schengen)",
        "cf": "Qualified",
        "ef": "No",
    },
    "dubrovnik-croatia-summer": {
        "bm": ["May", "Jun", "Sep", "Oct"],
        "rd": 5,
        "rc": "$2,200–$3,500",
        "fl": "14h 1-stop",
        "cb": {"flights": 1000, "hotels": 700, "food": 350, "activities": 300},
        "sn": "Warm Adriatic, fewer crowds in shoulder months, Old Town walks.",
        "sr": "High",
        "vr": "No (90-day visa-free)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "dubrovnik-to-split-coast-croatia-summer": {
        "bm": ["May", "Jun", "Sep"],
        "rd": 10,
        "rc": "$2,500–$4,000",
        "fl": "14h 1-stop",
        "cb": {"flights": 1000, "hotels": 900, "food": 400, "activities": 350},
        "sn": "Road-trip the Dalmatian coast: islands, old towns, and crystal water.",
        "sr": "High",
        "vr": "No (90-day visa-free)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "edinburgh-scotland-summer": {
        "bm": ["Jun", "Jul", "Aug"],
        "rd": 5,
        "rc": "$2,500–$4,000",
        "fl": "11h direct",
        "cb": {"flights": 900, "hotels": 1000, "food": 400, "activities": 300},
        "sn": "Festival season (Fringe in Aug), long daylight, castle views.",
        "sr": "High",
        "vr": "No (6-month visa-free)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "faroe-islands-summer": {
        "bm": ["Jun", "Jul", "Aug"],
        "rd": 6,
        "rc": "$3,000–$4,500",
        "fl": "13h 1-stop",
        "cb": {"flights": 1200, "hotels": 1000, "food": 500, "activities": 300},
        "sn": "Midnight sun, puffin colonies, dramatic cliffs, green valleys.",
        "sr": "High",
        "vr": "No (90-day Schengen via Denmark)",
        "cf": "Qualified",
        "ef": "Qualified",
    },
    "fez-morocco-summer": {
        "bm": ["Mar", "Apr", "May", "Oct", "Nov"],
        "rd": 5,
        "rc": "$1,500–$2,500",
        "fl": "14h 1-stop",
        "cb": {"flights": 800, "hotels": 300, "food": 200, "activities": 200},
        "sn": "Spring/fall best; summer is very hot but the medina stays atmospheric.",
        "sr": "Moderate",
        "vr": "No (90-day visa-free)",
        "cf": "Qualified",
        "ef": "No",
    },
    "florence-italy-summer": {
        "bm": ["Apr", "May", "Jun", "Sep", "Oct"],
        "rd": 5,
        "rc": "$2,800–$4,200",
        "fl": "13h 1-stop",
        "cb": {"flights": 1000, "hotels": 1000, "food": 500, "activities": 350},
        "sn": "Renaissance art, Tuscan wine country, rooftop sunsets.",
        "sr": "High",
        "vr": "No (90-day Schengen)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "galapagos-islands-ecuador-summer": {
        "bm": ["Jun", "Jul", "Aug", "Sep", "Oct", "Nov"],
        "rd": 8,
        "rc": "$4,000–$6,500",
        "fl": "10h 1-stop",
        "cb": {"flights": 1200, "hotels": 1200, "food": 500, "activities": 1000},
        "sn": "Cool/dry season: best snorkeling visibility, sea lion pups, albatross.",
        "sr": "High",
        "vr": "No (90-day visa-free)",
        "cf": "Qualified",
        "ef": "Qualified",
    },
    "grand-canyon-summer": {
        "bm": ["Mar", "Apr", "May", "Sep", "Oct"],
        "rd": 4,
        "rc": "$1,500–$2,500",
        "fl": "2h direct to PHX + 4h drive",
        "cb": {"flights": 300, "hotels": 600, "food": 300, "activities": 300},
        "sn": "Shoulder months avoid summer heat; South Rim open year-round.",
        "sr": "High",
        "vr": "No (domestic)",
        "cf": "Qualified",
        "ef": "Qualified",
    },
    "ha-long-bay-vietnam-summer": {
        "bm": ["Oct", "Nov", "Mar", "Apr"],
        "rd": 5,
        "rc": "$1,500–$2,500",
        "fl": "16h 1-stop",
        "cb": {"flights": 800, "hotels": 350, "food": 150, "activities": 250},
        "sn": "Summer is hot and stormy but dramatic; spring/fall best for cruises.",
        "sr": "Moderate",
        "vr": "E-visa required ($25)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "hanoi-vietnam-summer": {
        "bm": ["Oct", "Nov", "Mar", "Apr"],
        "rd": 7,
        "rc": "$1,500–$2,500",
        "fl": "16h 1-stop",
        "cb": {"flights": 800, "hotels": 350, "food": 150, "activities": 200},
        "sn": "Autumn/spring best; summer hot and rainy but vibrant street life.",
        "sr": "Moderate",
        "vr": "E-visa required ($25)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "havana-cuba-summer": {
        "bm": ["Nov", "Dec", "Jan", "Feb", "Mar", "Apr"],
        "rd": 7,
        "rc": "$2,000–$3,500",
        "fl": "6h 1-stop",
        "cb": {"flights": 500, "hotels": 700, "food": 300, "activities": 300},
        "sn": "Dry season best; summer humid with occasional hurricanes.",
        "sr": "Moderate",
        "vr": "Tourist card required ($50–$100)",
        "cf": "Qualified",
        "ef": "Qualified",
    },
    "hawaii": {
        "bm": ["Apr", "May", "Jun", "Sep", "Oct"],
        "rd": 10,
        "rc": "$3,000–$5,000",
        "fl": "5.5h direct",
        "cb": {"flights": 600, "hotels": 1500, "food": 600, "activities": 500},
        "sn": "Year-round warmth; shoulder months less crowded, great snorkeling.",
        "sr": "High",
        "vr": "No (domestic)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "iceland-summer": {
        "bm": ["Jun", "Jul", "Aug"],
        "rd": 10,
        "rc": "$3,500–$5,500",
        "fl": "8h direct",
        "cb": {"flights": 800, "hotels": 1500, "food": 600, "activities": 600},
        "sn": "Midnight sun, puffins, highland roads open, full Ring Road accessible.",
        "sr": "High",
        "vr": "No (90-day Schengen)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "istanbul-turkey-summer": {
        "bm": ["Apr", "May", "Jun", "Sep", "Oct"],
        "rd": 7,
        "rc": "$2,000–$3,500",
        "fl": "14h 1-stop",
        "cb": {"flights": 900, "hotels": 500, "food": 300, "activities": 300},
        "sn": "Warm, less crowded in shoulder months; rooftop dining, Bosphorus cruises.",
        "sr": "Moderate",
        "vr": "E-visa required ($50)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "jerusalem-israel-summer": {
        "bm": ["Mar", "Apr", "May", "Oct", "Nov"],
        "rd": 7,
        "rc": "$3,000–$4,500",
        "fl": "15h 1-stop",
        "cb": {"flights": 1100, "hotels": 1000, "food": 400, "activities": 300},
        "sn": "Spring/fall best; summer hot and dry but fewer European tourists.",
        "sr": "Moderate",
        "vr": "No (90-day visa-free)",
        "cf": "Qualified",
        "ef": "Qualified",
    },
    "jordan-summer": {
        "bm": ["Mar", "Apr", "May", "Oct", "Nov"],
        "rd": 8,
        "rc": "$2,000–$3,500",
        "fl": "16h 1-stop",
        "cb": {"flights": 1000, "hotels": 500, "food": 250, "activities": 400},
        "sn": "Spring/fall ideal for Petra and Wadi Rum; summer is scorching.",
        "sr": "Moderate",
        "vr": "Visa on arrival ($56, free with Jordan Pass)",
        "cf": "Qualified",
        "ef": "Qualified",
    },
    "kruger-national-park-south-africa": {
        "bm": ["May", "Jun", "Jul", "Aug", "Sep", "Oct"],
        "rd": 7,
        "rc": "$3,000–$5,000",
        "fl": "20h 1-stop",
        "cb": {"flights": 1200, "hotels": 800, "food": 350, "activities": 700},
        "sn": "Dry winter: thinner bush makes wildlife easier to spot. Big Five.",
        "sr": "Moderate",
        "vr": "No (90-day visa-free)",
        "cf": "Qualified",
        "ef": "Yes",
    },
    "kyoto-japan-summer": {
        "bm": ["Mar", "Apr", "Oct", "Nov"],
        "rd": 7,
        "rc": "$3,000–$4,500",
        "fl": "12h direct to KIX",
        "cb": {"flights": 1000, "hotels": 1000, "food": 500, "activities": 350},
        "sn": "Cherry blossoms (spring) and fall foliage are peak; summer is hot and humid.",
        "sr": "High",
        "vr": "No (90-day visa-free)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "kyrgyzstan-summer": {
        "bm": ["Jun", "Jul", "Aug", "Sep"],
        "rd": 10,
        "rc": "$1,500–$2,500",
        "fl": "16h 1-stop",
        "cb": {"flights": 800, "hotels": 300, "food": 150, "activities": 300},
        "sn": "Mountain passes open, yurt stays, horseback trekking, Song Kul lake.",
        "sr": "Moderate",
        "vr": "No (60-day visa-free)",
        "cf": "Qualified",
        "ef": "No",
    },
    "lima-peru": {
        "bm": ["Dec", "Jan", "Feb", "Mar"],
        "rd": 5,
        "rc": "$1,800–$3,000",
        "fl": "9h direct",
        "cb": {"flights": 600, "hotels": 500, "food": 350, "activities": 250},
        "sn": "Southern summer: sunny, warm, ceviche season, beach weather.",
        "sr": "Moderate",
        "vr": "No (183-day visa-free)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "lisbon-portugal-summer": {
        "bm": ["May", "Jun", "Jul", "Sep", "Oct"],
        "rd": 6,
        "rc": "$2,200–$3,500",
        "fl": "11h direct",
        "cb": {"flights": 800, "hotels": 700, "food": 350, "activities": 300},
        "sn": "Warm, vibrant, rooftop bars, pastéis de nata, nearby beaches.",
        "sr": "High",
        "vr": "No (90-day Schengen)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "lofoten-islands-norway-summer": {
        "bm": ["Jun", "Jul", "Aug"],
        "rd": 7,
        "rc": "$3,500–$5,000",
        "fl": "14h 1-stop",
        "cb": {"flights": 1200, "hotels": 1200, "food": 500, "activities": 400},
        "sn": "Midnight sun, dramatic peaks, fishing villages, Arctic surfing.",
        "sr": "High",
        "vr": "No (90-day Schengen)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "london-england-summer": {
        "bm": ["May", "Jun", "Jul", "Aug", "Sep"],
        "rd": 7,
        "rc": "$3,000–$5,000",
        "fl": "10.5h direct",
        "cb": {"flights": 900, "hotels": 1300, "food": 500, "activities": 400},
        "sn": "Parks in bloom, outdoor theatre, long evenings, Wimbledon.",
        "sr": "High",
        "vr": "No (6-month visa-free)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "luang-prabang-laos-summer": {
        "bm": ["Nov", "Dec", "Jan", "Feb", "Mar"],
        "rd": 5,
        "rc": "$1,200–$2,000",
        "fl": "18h 1-stop",
        "cb": {"flights": 800, "hotels": 200, "food": 100, "activities": 150},
        "sn": "Dry season: alms-giving, waterfalls at full flow, Mekong cruises.",
        "sr": "High",
        "vr": "Visa on arrival ($40)",
        "cf": "Qualified",
        "ef": "Qualified",
    },
    "machu-picchu-peru-summer": {
        "bm": ["May", "Jun", "Jul", "Aug", "Sep"],
        "rd": 5,
        "rc": "$2,500–$4,000",
        "fl": "12h 1-stop",
        "cb": {"flights": 700, "hotels": 600, "food": 250, "activities": 700},
        "sn": "Dry season: clear views, Inca Trail open, cool mornings.",
        "sr": "Moderate",
        "vr": "No (183-day visa-free)",
        "cf": "Qualified",
        "ef": "No",
    },
    "madagascar-summer": {
        "bm": ["Apr", "May", "Sep", "Oct", "Nov"],
        "rd": 12,
        "rc": "$3,000–$5,000",
        "fl": "22h 2-stop",
        "cb": {"flights": 1500, "hotels": 600, "food": 250, "activities": 600},
        "sn": "Shoulder months: lemurs active, whale season (Jul–Sep), dry weather.",
        "sr": "Moderate",
        "vr": "Visa on arrival ($35)",
        "cf": "No",
        "ef": "No",
    },
    "madrid-spain-summer": {
        "bm": ["Apr", "May", "Jun", "Sep", "Oct"],
        "rd": 5,
        "rc": "$2,200–$3,500",
        "fl": "12h direct",
        "cb": {"flights": 800, "hotels": 700, "food": 400, "activities": 300},
        "sn": "Prado, tapas crawls, rooftop bars; avoid July–Aug peak heat.",
        "sr": "High",
        "vr": "No (90-day Schengen)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "maldives-summer": {
        "bm": ["Jan", "Feb", "Mar", "Apr"],
        "rd": 7,
        "rc": "$4,000–$7,000",
        "fl": "18h 1-stop",
        "cb": {"flights": 1500, "hotels": 3000, "food": 600, "activities": 500},
        "sn": "Dry northeast monsoon; summer is cheaper but wetter, still great diving.",
        "sr": "High",
        "vr": "Free 30-day visa on arrival",
        "cf": "Qualified",
        "ef": "Yes",
    },
    "marrakech-morocco-summer": {
        "bm": ["Mar", "Apr", "May", "Oct", "Nov"],
        "rd": 5,
        "rc": "$1,500–$2,500",
        "fl": "14h 1-stop",
        "cb": {"flights": 800, "hotels": 350, "food": 200, "activities": 200},
        "sn": "Spring/fall ideal; summer is extremely hot but the souks stay bustling.",
        "sr": "Moderate",
        "vr": "No (90-day visa-free)",
        "cf": "Qualified",
        "ef": "Qualified",
    },
    "masai-mara-kenya-summer": {
        "bm": ["Jul", "Aug", "Sep", "Oct"],
        "rd": 7,
        "rc": "$3,500–$6,000",
        "fl": "20h 1-stop",
        "cb": {"flights": 1300, "hotels": 1200, "food": 400, "activities": 1000},
        "sn": "Great Migration river crossings (Jul–Oct); peak safari season.",
        "sr": "Moderate",
        "vr": "E-visa required ($51)",
        "cf": "Qualified",
        "ef": "Qualified",
    },
    "melbourne-australia": {
        "bm": ["Nov", "Dec", "Jan", "Feb", "Mar"],
        "rd": 7,
        "rc": "$3,000–$4,500",
        "fl": "16h direct",
        "cb": {"flights": 1200, "hotels": 1000, "food": 500, "activities": 350},
        "sn": "Southern summer: Great Ocean Road, coffee culture, outdoor festivals.",
        "sr": "High",
        "vr": "ETA required ($20)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "mexico-city-mexico-summer": {
        "bm": ["Mar", "Apr", "May", "Oct", "Nov"],
        "rd": 7,
        "rc": "$1,800–$3,000",
        "fl": "4.5h direct",
        "cb": {"flights": 400, "hotels": 600, "food": 350, "activities": 300},
        "sn": "Dry season; rainy season (Jun–Sep) has afternoon showers, green parks.",
        "sr": "Moderate",
        "vr": "No (180-day visa-free)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "montenegro-summer": {
        "bm": ["Jun", "Jul", "Aug", "Sep"],
        "rd": 7,
        "rc": "$1,800–$3,000",
        "fl": "14h 1-stop",
        "cb": {"flights": 900, "hotels": 500, "food": 250, "activities": 250},
        "sn": "Adriatic beaches, Bay of Kotor, Durmitor hiking, affordable luxury.",
        "sr": "High",
        "vr": "No (90-day visa-free)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "montreal-canada-summer": {
        "bm": ["Jun", "Jul", "Aug", "Sep"],
        "rd": 5,
        "rc": "$2,000–$3,500",
        "fl": "5.5h direct",
        "cb": {"flights": 500, "hotels": 800, "food": 400, "activities": 300},
        "sn": "Jazz festival, patio culture, Jean-Talon market, cycling paths.",
        "sr": "High",
        "vr": "No (eTA required)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "namibia-summer": {
        "bm": ["May", "Jun", "Jul", "Aug", "Sep", "Oct"],
        "rd": 12,
        "rc": "$3,000–$5,000",
        "fl": "20h 1-stop",
        "cb": {"flights": 1400, "hotels": 800, "food": 300, "activities": 600},
        "sn": "Dry season: Etosha waterholes busy, Sossusvlei stunning, clear skies.",
        "sr": "High",
        "vr": "No (90-day visa-free)",
        "cf": "Qualified",
        "ef": "Qualified",
    },
    "new-york-city-summer": {
        "bm": ["May", "Jun", "Sep", "Oct"],
        "rd": 7,
        "rc": "$3,000–$5,000",
        "fl": "5.5h direct",
        "cb": {"flights": 400, "hotels": 1500, "food": 600, "activities": 500},
        "sn": "Central Park, rooftop bars, Broadway, summer concerts.",
        "sr": "High",
        "vr": "No (domestic)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "new-zealand-south-island": {
        "bm": ["Nov", "Dec", "Jan", "Feb", "Mar"],
        "rd": 14,
        "rc": "$3,500–$5,500",
        "fl": "13h direct to AKL + domestic",
        "cb": {"flights": 1200, "hotels": 1200, "food": 500, "activities": 600},
        "sn": "Summer: Milford Sound, glaciers, hiking, Great Walks open.",
        "sr": "High",
        "vr": "NZeTA required ($12)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "norwegian-fjords-summer": {
        "bm": ["Jun", "Jul", "Aug"],
        "rd": 8,
        "rc": "$3,500–$5,500",
        "fl": "12h 1-stop",
        "cb": {"flights": 1000, "hotels": 1400, "food": 600, "activities": 500},
        "sn": "Midnight sun, fjord cruises, trolltunga hikes, lush valleys.",
        "sr": "High",
        "vr": "No (90-day Schengen)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "oaxaca-mexico-summer": {
        "bm": ["Oct", "Nov", "Dec", "Mar", "Apr"],
        "rd": 7,
        "rc": "$1,500–$2,500",
        "fl": "6h 1-stop",
        "cb": {"flights": 500, "hotels": 400, "food": 250, "activities": 250},
        "sn": "Day of the Dead (Nov), mole cuisine, mezcal, Hierve el Agua.",
        "sr": "Moderate",
        "vr": "No (180-day visa-free)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "oman": {
        "bm": ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
        "rd": 8,
        "rc": "$2,500–$4,000",
        "fl": "18h 1-stop",
        "cb": {"flights": 1100, "hotels": 700, "food": 350, "activities": 400},
        "sn": "Cooler months: wadis, dunes, frankincense trail, snorkeling Musandam.",
        "sr": "High",
        "vr": "E-visa required ($20)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "palawan-philippines-summer": {
        "bm": ["Nov", "Dec", "Jan", "Feb", "Mar", "Apr"],
        "rd": 8,
        "rc": "$1,800–$3,000",
        "fl": "16h 1-stop",
        "cb": {"flights": 800, "hotels": 500, "food": 200, "activities": 350},
        "sn": "Dry season: El Nido island hopping, underground river, crystal lagoons.",
        "sr": "Moderate",
        "vr": "No (30-day visa-free)",
        "cf": "Qualified",
        "ef": "Qualified",
    },
    "pantanal-brazil-summer": {
        "bm": ["Jul", "Aug", "Sep", "Oct"],
        "rd": 7,
        "rc": "$2,500–$4,000",
        "fl": "16h 1-stop",
        "cb": {"flights": 1000, "hotels": 700, "food": 300, "activities": 600},
        "sn": "Dry season: wildlife concentrates at water sources, jaguars visible.",
        "sr": "Moderate",
        "vr": "No (90-day visa-free)",
        "cf": "Qualified",
        "ef": "No",
    },
    "paris-france-summer": {
        "bm": ["May", "Jun", "Jul", "Sep", "Oct"],
        "rd": 7,
        "rc": "$3,000–$5,000",
        "fl": "11h direct",
        "cb": {"flights": 900, "hotels": 1300, "food": 500, "activities": 400},
        "sn": "Terraces alive, Seine picnics, museums, Bastille Day fireworks.",
        "sr": "Moderate",
        "vr": "No (90-day Schengen)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "patagonia-argentina": {
        "bm": ["Nov", "Dec", "Jan", "Feb", "Mar"],
        "rd": 12,
        "rc": "$3,000–$5,000",
        "fl": "16h 1-stop",
        "cb": {"flights": 1200, "hotels": 900, "food": 400, "activities": 600},
        "sn": "Southern summer: glaciers, Torres del Paine day trips, long daylight.",
        "sr": "High",
        "vr": "No (90-day visa-free)",
        "cf": "Qualified",
        "ef": "No",
    },
    "petra-jordan-summer": {
        "bm": ["Mar", "Apr", "May", "Oct", "Nov"],
        "rd": 4,
        "rc": "$2,000–$3,500",
        "fl": "16h 1-stop",
        "cb": {"flights": 1000, "hotels": 500, "food": 200, "activities": 400},
        "sn": "Spring/fall: comfortable walking temps for the Siq and Treasury.",
        "sr": "Moderate",
        "vr": "Visa on arrival ($56, free with Jordan Pass)",
        "cf": "Qualified",
        "ef": "No",
    },
    "plitvice-lakes-croatia-summer": {
        "bm": ["May", "Jun", "Sep", "Oct"],
        "rd": 3,
        "rc": "$1,500–$2,500",
        "fl": "14h 1-stop",
        "cb": {"flights": 1000, "hotels": 300, "food": 150, "activities": 150},
        "sn": "Waterfalls at full volume in spring; fewer crowds in shoulder months.",
        "sr": "High",
        "vr": "No (90-day visa-free)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "prague-czech-republic-summer": {
        "bm": ["May", "Jun", "Jul", "Aug", "Sep"],
        "rd": 5,
        "rc": "$1,800–$3,000",
        "fl": "13h 1-stop",
        "cb": {"flights": 900, "hotels": 500, "food": 250, "activities": 250},
        "sn": "Golden hour on Charles Bridge, beer gardens, river cruises.",
        "sr": "High",
        "vr": "No (90-day Schengen)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "provence-france-summer": {
        "bm": ["Jun", "Jul", "Aug"],
        "rd": 8,
        "rc": "$2,800–$4,500",
        "fl": "12h 1-stop",
        "cb": {"flights": 1000, "hotels": 1000, "food": 500, "activities": 350},
        "sn": "Lavender fields bloom, rosé season, open-air markets, cicadas.",
        "sr": "High",
        "vr": "No (90-day Schengen)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "queenstown-new-zealand": {
        "bm": ["Nov", "Dec", "Jan", "Feb", "Mar"],
        "rd": 7,
        "rc": "$3,000–$5,000",
        "fl": "14h 1-stop",
        "cb": {"flights": 1200, "hotels": 1000, "food": 450, "activities": 600},
        "sn": "Summer: bungee, hiking, jet boats, Milford Sound day trips.",
        "sr": "High",
        "vr": "NZeTA required ($12)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "raja-ampat-indonesia-summer": {
        "bm": ["Oct", "Nov", "Dec", "Apr", "May"],
        "rd": 8,
        "rc": "$3,000–$5,000",
        "fl": "20h 2-stop",
        "cb": {"flights": 1500, "hotels": 800, "food": 300, "activities": 600},
        "sn": "Calm seas and best visibility for world-class diving and snorkeling.",
        "sr": "Moderate",
        "vr": "No (30-day visa-free)",
        "cf": "No",
        "ef": "No",
    },
    "rome-italy-summer": {
        "bm": ["Apr", "May", "Jun", "Sep", "Oct"],
        "rd": 7,
        "rc": "$2,800–$4,500",
        "fl": "13h direct",
        "cb": {"flights": 1000, "hotels": 1000, "food": 500, "activities": 350},
        "sn": "Ancient ruins, Vatican, aperitivo culture; shoulder months beat the heat.",
        "sr": "Moderate",
        "vr": "No (90-day Schengen)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "san-sebastian-spain-summer": {
        "bm": ["Jun", "Jul", "Aug", "Sep"],
        "rd": 5,
        "rc": "$2,500–$4,000",
        "fl": "12h 1-stop",
        "cb": {"flights": 900, "hotels": 900, "food": 500, "activities": 250},
        "sn": "Beach season, pintxos crawls, world-class dining, film festival (Sep).",
        "sr": "High",
        "vr": "No (90-day Schengen)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "santorini-greece-summer": {
        "bm": ["May", "Jun", "Sep", "Oct"],
        "rd": 5,
        "rc": "$3,000–$5,000",
        "fl": "14h 1-stop",
        "cb": {"flights": 1000, "hotels": 1200, "food": 400, "activities": 350},
        "sn": "Caldera sunsets, blue-domed churches, volcanic beaches, wine tours.",
        "sr": "High",
        "vr": "No (90-day Schengen)",
        "cf": "Qualified",
        "ef": "Qualified",
    },
    "sardinia-italy-summer": {
        "bm": ["Jun", "Jul", "Aug", "Sep"],
        "rd": 8,
        "rc": "$2,500–$4,000",
        "fl": "14h 1-stop",
        "cb": {"flights": 1100, "hotels": 900, "food": 400, "activities": 350},
        "sn": "Costa Smeralda beaches, ancient nuraghi, pecorino cheese, clear waters.",
        "sr": "High",
        "vr": "No (90-day Schengen)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "scottish-highlands-summer": {
        "bm": ["Jun", "Jul", "Aug"],
        "rd": 8,
        "rc": "$2,500–$4,000",
        "fl": "11h 1-stop",
        "cb": {"flights": 900, "hotels": 900, "food": 400, "activities": 350},
        "sn": "Long daylight, whisky distilleries, castles, highland wildlife.",
        "sr": "High",
        "vr": "No (6-month visa-free)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "seoul-south-korea-summer": {
        "bm": ["Apr", "May", "Sep", "Oct", "Nov"],
        "rd": 7,
        "rc": "$2,500–$4,000",
        "fl": "11h direct",
        "cb": {"flights": 800, "hotels": 800, "food": 400, "activities": 350},
        "sn": "Fall foliage and cherry blossoms (spring) are magical; summer is monsoon.",
        "sr": "High",
        "vr": "K-ETA required ($10)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "serengeti-tanzania-summer": {
        "bm": ["Jun", "Jul", "Aug", "Sep", "Oct"],
        "rd": 8,
        "rc": "$4,000–$7,000",
        "fl": "20h 1-stop",
        "cb": {"flights": 1500, "hotels": 1500, "food": 400, "activities": 1200},
        "sn": "Great Migration in full swing: river crossings, predator action.",
        "sr": "Moderate",
        "vr": "E-visa required ($50)",
        "cf": "Qualified",
        "ef": "Qualified",
    },
    "siem-reap-cambodia-summer": {
        "bm": ["Nov", "Dec", "Jan", "Feb", "Mar"],
        "rd": 5,
        "rc": "$1,200–$2,000",
        "fl": "18h 1-stop",
        "cb": {"flights": 800, "hotels": 200, "food": 100, "activities": 200},
        "sn": "Dry season: sunrise at Angkor Wat, temple hopping, floating villages.",
        "sr": "Moderate",
        "vr": "Visa on arrival ($30)",
        "cf": "Qualified",
        "ef": "Qualified",
    },
    "singapore": {
        "bm": ["Feb", "Mar", "Apr", "May", "Jun", "Jul"],
        "rd": 5,
        "rc": "$2,500–$4,000",
        "fl": "17h direct",
        "cb": {"flights": 900, "hotels": 900, "food": 400, "activities": 300},
        "sn": "Year-round tropical; drier Feb–Apr. Gardens, hawker centers, Marina Bay.",
        "sr": "High",
        "vr": "No (90-day visa-free)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "slovenia-summer": {
        "bm": ["Jun", "Jul", "Aug", "Sep"],
        "rd": 7,
        "rc": "$1,800–$3,000",
        "fl": "13h 1-stop",
        "cb": {"flights": 900, "hotels": 500, "food": 250, "activities": 300},
        "sn": "Lake Bled, Triglav hiking, Ljubljana cafe scene, Adriatic coast.",
        "sr": "High",
        "vr": "No (90-day Schengen)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "sri-lanka-summer": {
        "bm": ["Dec", "Jan", "Feb", "Mar", "Jul", "Aug"],
        "rd": 12,
        "rc": "$1,800–$3,000",
        "fl": "20h 1-stop",
        "cb": {"flights": 1000, "hotels": 400, "food": 200, "activities": 300},
        "sn": "East coast dry Jul–Aug; west coast dry Dec–Mar. Safaris, tea country, temples.",
        "sr": "Moderate",
        "vr": "ETA required ($50)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "st-petersburg-russia-summer": {
        "bm": ["Jun", "Jul"],
        "rd": 6,
        "rc": "$2,000–$3,500",
        "fl": "14h 1-stop",
        "cb": {"flights": 900, "hotels": 600, "food": 300, "activities": 300},
        "sn": "White Nights: Hermitage, palaces, canals bathed in 24h light.",
        "sr": "Moderate",
        "vr": "Visa required (varies, check current status)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "svalbard-norway-summer": {
        "bm": ["Jun", "Jul", "Aug"],
        "rd": 5,
        "rc": "$3,500–$5,500",
        "fl": "15h 1-stop",
        "cb": {"flights": 1500, "hotels": 1200, "food": 500, "activities": 600},
        "sn": "24h daylight, polar bear safaris, glacier kayaking, Arctic wildflowers.",
        "sr": "High",
        "vr": "No (Svalbard is visa-free for all)",
        "cf": "No",
        "ef": "No",
    },
    "swiss-alps-summer": {
        "bm": ["Jun", "Jul", "Aug", "Sep"],
        "rd": 8,
        "rc": "$3,500–$5,500",
        "fl": "12h direct to ZRH",
        "cb": {"flights": 1000, "hotels": 1500, "food": 600, "activities": 500},
        "sn": "Alpine hiking, Jungfrau region, wildflower meadows, scenic trains.",
        "sr": "High",
        "vr": "No (90-day Schengen)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "taipei-taiwan-summer": {
        "bm": ["Oct", "Nov", "Mar", "Apr", "May"],
        "rd": 7,
        "rc": "$2,000–$3,500",
        "fl": "12h direct",
        "cb": {"flights": 800, "hotels": 600, "food": 300, "activities": 300},
        "sn": "Night markets, temples, Taroko Gorge; spring/fall avoid typhoon season.",
        "sr": "High",
        "vr": "No (90-day visa-free)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "tasmania-australia": {
        "bm": ["Dec", "Jan", "Feb", "Mar"],
        "rd": 10,
        "rc": "$3,000–$4,500",
        "fl": "18h 1-stop",
        "cb": {"flights": 1300, "hotels": 900, "food": 450, "activities": 400},
        "sn": "Southern summer: Overland Track, MONA, Cradle Mountain, fresh seafood.",
        "sr": "High",
        "vr": "ETA required ($20)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "tbilisi-georgia-summer": {
        "bm": ["May", "Jun", "Sep", "Oct"],
        "rd": 8,
        "rc": "$1,500–$2,500",
        "fl": "16h 1-stop",
        "cb": {"flights": 900, "hotels": 300, "food": 150, "activities": 200},
        "sn": "Wine country, sulfur baths, Caucasus hiking, incredibly affordable.",
        "sr": "Moderate",
        "vr": "No (365-day visa-free)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "tokyo-japan-summer": {
        "bm": ["Mar", "Apr", "Oct", "Nov"],
        "rd": 8,
        "rc": "$3,000–$5,000",
        "fl": "11h direct",
        "cb": {"flights": 900, "hotels": 1100, "food": 600, "activities": 400},
        "sn": "Cherry blossoms (spring) or fall foliage; summer is hot/humid but festive.",
        "sr": "High",
        "vr": "No (90-day visa-free)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "torres-del-paine-chile": {
        "bm": ["Nov", "Dec", "Jan", "Feb"],
        "rd": 8,
        "rc": "$3,000–$5,000",
        "fl": "16h 1-stop",
        "cb": {"flights": 1200, "hotels": 900, "food": 350, "activities": 600},
        "sn": "Southern summer: W Trek open, stable weather, long daylight.",
        "sr": "High",
        "vr": "No (90-day visa-free)",
        "cf": "No",
        "ef": "No",
    },
    "uganda-summer": {
        "bm": ["Jun", "Jul", "Aug", "Sep", "Dec", "Jan", "Feb"],
        "rd": 10,
        "rc": "$3,500–$6,000",
        "fl": "20h 1-stop",
        "cb": {"flights": 1300, "hotels": 800, "food": 300, "activities": 1500},
        "sn": "Dry seasons: gorilla trekking, tree-climbing lions, Nile rafting.",
        "sr": "Moderate",
        "vr": "E-visa required ($50)",
        "cf": "No",
        "ef": "No",
    },
    "varanasi-india-summer": {
        "bm": ["Oct", "Nov", "Feb", "Mar"],
        "rd": 5,
        "rc": "$1,500–$2,500",
        "fl": "20h 1-stop",
        "cb": {"flights": 900, "hotels": 200, "food": 100, "activities": 200},
        "sn": "Post-monsoon or spring: Ganges ceremonies, silk weaving, ancient temples.",
        "sr": "Moderate",
        "vr": "E-visa required ($25)",
        "cf": "No",
        "ef": "No",
    },
    "vienna-austria-summer": {
        "bm": ["May", "Jun", "Jul", "Aug", "Sep"],
        "rd": 5,
        "rc": "$2,500–$4,000",
        "fl": "13h 1-stop",
        "cb": {"flights": 1000, "hotels": 800, "food": 400, "activities": 350},
        "sn": "Palace gardens, outdoor concerts, Danube cycling, coffee house culture.",
        "sr": "High",
        "vr": "No (90-day Schengen)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "washington-dc-summer": {
        "bm": ["Mar", "Apr", "May", "Sep", "Oct"],
        "rd": 5,
        "rc": "$2,000–$3,500",
        "fl": "5.5h direct",
        "cb": {"flights": 400, "hotels": 1000, "food": 400, "activities": 200},
        "sn": "Cherry blossoms (late Mar/Apr), free Smithsonians, fall colors.",
        "sr": "High",
        "vr": "No (domestic)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "yellowstone-summer": {
        "bm": ["Jun", "Jul", "Aug", "Sep"],
        "rd": 5,
        "rc": "$2,000–$3,500",
        "fl": "3h direct to BZN + 1.5h drive",
        "cb": {"flights": 400, "hotels": 800, "food": 400, "activities": 400},
        "sn": "All roads open, geysers, bison herds, bear sightings, wildflowers.",
        "sr": "High",
        "vr": "No (domestic)",
        "cf": "Yes",
        "ef": "Qualified",
    },
    "zanzibar-tanzania-summer": {
        "bm": ["Jun", "Jul", "Aug", "Sep", "Jan", "Feb"],
        "rd": 7,
        "rc": "$2,000–$3,500",
        "fl": "20h 1-stop",
        "cb": {"flights": 1200, "hotels": 500, "food": 200, "activities": 300},
        "sn": "Dry seasons: spice tours, Stone Town, turquoise beaches, diving.",
        "sr": "Moderate",
        "vr": "E-visa required ($50)",
        "cf": "Yes",
        "ef": "Yes",
    },
    "zhangjiajie-china-summer": {
        "bm": ["Apr", "May", "Sep", "Oct", "Nov"],
        "rd": 5,
        "rc": "$2,000–$3,500",
        "fl": "14h 1-stop",
        "cb": {"flights": 900, "hotels": 400, "food": 200, "activities": 350},
        "sn": "Avatar mountains, glass bridge; spring/fall avoid summer crowds and rain.",
        "sr": "High",
        "vr": "144h transit visa-free (or 10-year visa $140)",
        "cf": "Qualified",
        "ef": "No",
    },
}


def enrich_file(filepath: Path, dry_run: bool = False) -> bool:
    """Enrich a single destination JSON file. Returns True if modified."""
    slug = filepath.stem
    if slug not in ENRICHMENT:
        return False

    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)

    enrichment = ENRICHMENT[slug]
    modified = False

    field_map = {
        "bm": "best_months",
        "rd": "recommended_days",
        "rc": "rough_cost",
        "fl": "flight_duration_from_sfo",
        "cb": "cost_breakdown",
        "sn": "seasonal_note",
        "sr": "safety_rating",
        "vr": "visa_required",
        "cf": "child_friendly",
        "ef": "elderly_friendly",
    }

    for short_key, full_key in field_map.items():
        if short_key not in enrichment:
            continue
        current = data.get(full_key)
        # Only overwrite if current value is empty/default
        if current in (None, "", 0, [], {}, "Unknown"):
            data[full_key] = enrichment[short_key]
            modified = True

    if modified and not dry_run:
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

    return modified


def main():
    parser = argparse.ArgumentParser(description="Enrich destination data")
    parser.add_argument("--dry-run", action="store_true", help="Preview without writing")
    args = parser.parse_args()

    if not DATA_DIR.exists():
        print(f"Error: {DATA_DIR} not found")
        return

    files = sorted(DATA_DIR.glob("*.json"))
    enriched = 0
    skipped = 0
    missing = 0

    for f in files:
        slug = f.stem
        if slug not in ENRICHMENT:
            print(f"  MISSING lookup: {slug}")
            missing += 1
            continue

        if enrich_file(f, dry_run=args.dry_run):
            enriched += 1
            print(f"  {'[DRY RUN] ' if args.dry_run else ''}Enriched: {slug}")
        else:
            skipped += 1

    print(f"\nDone: {enriched} enriched, {skipped} already complete, {missing} missing lookup")


if __name__ == "__main__":
    main()
